### ISSUE TITLE
[Feature request] Don't block UI when control is open

### ISSUE THREAD

**Issue by FokkenClown** [Manvaril/vehcontrol#9]
**Is your feature request related to a problem? Please describe.**
If the UI is open it blocks all inputs, so you cannot continue driving or use any other ui function

**Describe the solution you'd like**
Having the UI open and still be able to use other functions, like phone, driving etc

**Comment by Manvaril** [comment]
After looking into this, it won't be implemented due to technical issue with FiveM. I did get movement control but you also looked around while trying to use the menu and when you hit ESC to close the menu the pause/map would also open. This is mostly an issue with using the mouse with a menu resource like this.
